### ISSUE TITLE
Build failure with GHC 7.8.1-rc1

### ISSUE THREAD

**Issue by peti** [sedillard/Vec#5]
The build errors are:

```
Data/Vec/LinAlg.hs:237:10:
    Illegal instance declaration for ``SetDiagonal v m''
      The liberal coverage condition fails in class ``SetDiagonal''
        for functional dependency: ``m -> v''
      Reason: lhs type ``m'' does not determine rhs type ``v''
    In the instance declaration for ``SetDiagonal v m''

Data/Vec/LinAlg.hs:576:10:
    Illegal instance declaration for ``Pivot a (() :. v)''
      The liberal coverage condition fails in class ``Pivot''
        for functional dependency: ``m -> a''
      Reason: lhs type ``() :. v'' does not determine rhs type ``a''
    In the instance declaration for ``Pivot a (() :. v)''
```

A complete log file is available at http://hydra.cryp.to/build/43940/nixlog/1/raw.

**Comment by listx** [comment]
Here is a stackoverflow page with a similar discussion: http://stackoverflow.com/questions/20778588/liberal-coverage-condition-introduced-in-ghc-7-7-breaks-code-valid-in-ghc-7-6

**Comment by sedillard** [comment]
Ok please try now. I tested examples/Examples.hs and examples/Overlap.hs and they both build, but that is not a very thorough test. But at least it builds now.

Thanks for the report.

**Comment by listx** [comment]
It works, thank you!

**Comment by wdanilo** [comment]
The version available in hackage still has this bug!

**Comment by sedillard** [comment]
Sorry for the delay. Hackage is now updated to 1.0.5
